# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

pod 'Alamofire'
pod 'SwiftyJSON'
pod 'Alamofire-SwiftyJSON', git: 'https://github.com/SwiftyJSON/Alamofire-SwiftyJSON'

target 'sample' do

end

target 'sampleTests' do

end

